//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTrackerFinal.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Game_info
    {
        public int gameID { get; set; }
        public string gameType { get; set; }
        public Nullable<int> team1ID { get; set; }
        public Nullable<int> team2ID { get; set; }
        public string team1Name { get; set; }
        public string team2Name { get; set; }
        public Nullable<int> team1Score { get; set; }
        public Nullable<int> team2Score { get; set; }
        public string gameWinner { get; set; }
        public Nullable<System.DateTime> weeks { get; set; }
    }
}
